---
device_os: ios
provider: "{{ cli }}"

cli:
  host: "{{ ios_cli_host | default(inventory_hostname) }}"
  username: "{{ admin | default('cisco') }}"
  password: "{{ NORX_lab18 | default('cisco') }}"
  transport: cli
  authorize: yes
