---
- name: Configure ACL for IOS
  ios_config:
    lines: "{{ voice_acl }}"
    parents: ['ip access-list extended TESTING_NOW']
    before: ['no ip access-list extended TESTING_NOW']
    match: exact
    replace: block
    host: "{{ inventory_hostname }}"
    username: admin
  register: output
