---
- name: collect output from ios device
  ios_command:
    commands:
      - show version
      - show interfaces
      - show running-config
    provider: "{{ cli }}"
  register: output

# common facts
#
  debug: var=output
