---
- name: collect output from ios device
  ios_command:
    commands:
      - show version
      - show interfaces
      - show running-config
    provider: "{{ cli }}"
  register: output

# common facts
#
- name: Test debug
  debug: var=output.stdout[2]
- name: set hostname fact
  set_fact: hostname="{{ (output.stdout[2] | regex_search('hostname (.+)', '\\1') | first) }}"
- name: Test fact
  debug: var=hostname
